package com.neko.model;
// Generated 31 mars 2016 00:28:36 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Astuces generated by hbm2java
 */
@Entity
@Table(name = "astuces", catalog = "bd")
public class Astuces implements java.io.Serializable {

	private Integer idAstuces;
	private Chat chat;
	private Utilisateur utilisateur;
	private String commentaire;

	public Astuces() {
	}

	public Astuces(Chat chat, Utilisateur utilisateur, String commentaire) {
		this.chat = chat;
		this.utilisateur = utilisateur;
		this.commentaire = commentaire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_astuces", unique = true, nullable = false)
	public Integer getIdAstuces() {
		return this.idAstuces;
	}

	public void setIdAstuces(Integer idAstuces) {
		this.idAstuces = idAstuces;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nom_chat", nullable = false)
	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "commentaire", nullable = false, length = 300)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

}
