package com.neko.model;
// Generated 31 mars 2016 00:28:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chat generated by hbm2java
 */
@Entity
@Table(name = "chat", catalog = "bd")
public class Chat implements java.io.Serializable {

	private String nomChat;
	private String nomJaponnais;
	private String couleur;
	private String caractere;
	private int niveau;
	private String image;
	private String description;
	private Set<Astuces> astuceses = new HashSet<Astuces>(0);

	public Chat() {
	}

	public Chat(String nomChat, String nomJaponnais, String couleur, String caractere, int niveau, String image,
			String description) {
		this.nomChat = nomChat;
		this.nomJaponnais = nomJaponnais;
		this.couleur = couleur;
		this.caractere = caractere;
		this.niveau = niveau;
		this.image = image;
		this.description = description;
	}

	public Chat(String nomChat, String nomJaponnais, String couleur, String caractere, int niveau, String image,
			String description, Set<Astuces> astuceses) {
		this.nomChat = nomChat;
		this.nomJaponnais = nomJaponnais;
		this.couleur = couleur;
		this.caractere = caractere;
		this.niveau = niveau;
		this.image = image;
		this.description = description;
		this.astuceses = astuceses;
	}

	@Id

	@Column(name = "nom_chat", unique = true, nullable = false, length = 100)
	public String getNomChat() {
		return this.nomChat;
	}

	public void setNomChat(String nomChat) {
		this.nomChat = nomChat;
	}

	@Column(name = "nom_japonnais", nullable = false, length = 100)
	public String getNomJaponnais() {
		return this.nomJaponnais;
	}

	public void setNomJaponnais(String nomJaponnais) {
		this.nomJaponnais = nomJaponnais;
	}

	@Column(name = "couleur", nullable = false, length = 50)
	public String getCouleur() {
		return this.couleur;
	}

	public void setCouleur(String couleur) {
		this.couleur = couleur;
	}

	@Column(name = "caractere", nullable = false, length = 30)
	public String getCaractere() {
		return this.caractere;
	}

	public void setCaractere(String caractere) {
		this.caractere = caractere;
	}

	@Column(name = "niveau", nullable = false)
	public int getNiveau() {
		return this.niveau;
	}

	public void setNiveau(int niveau) {
		this.niveau = niveau;
	}

	@Column(name = "image", nullable = false, length = 100)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "description", nullable = false, length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chat")
	public Set<Astuces> getAstuceses() {
		return this.astuceses;
	}

	public void setAstuceses(Set<Astuces> astuceses) {
		this.astuceses = astuceses;
	}

}
