package com.neko.model;
// Generated 2 avr. 2016 23:22:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name = "compte", catalog = "chatbd")
public class Compte implements java.io.Serializable {

	private String login;
	private Utilisateur utilisateur;
	private String motdepasse;
	private String email;
	private Set<Astuces> astuceses = new HashSet<Astuces>(0);
	private Set<Chat> chats = new HashSet<Chat>(0);

	public Compte() {
	}

	public Compte(String login, String motdepasse, String email) {
		this.login = login;
		this.motdepasse = motdepasse;
		this.email = email;
	} 
	public Compte(String login, Utilisateur utilisateur, String motdepasse, String email) {
		this.login = login;
		this.utilisateur = utilisateur;
		this.motdepasse = motdepasse;
		this.email = email;
	}

	public Compte(String login, Utilisateur utilisateur, String motdepasse, String email, Set<Astuces> astuceses,
			Set<Chat> chats) {
		this.login = login;
		this.utilisateur = utilisateur;
		this.motdepasse = motdepasse;
		this.email = email;
		this.astuceses = astuceses;
		this.chats = chats;
	}

	@Id

	@Column(name = "login", unique = true, nullable = false, length = 20)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "idutilisateur", nullable = false, columnDefinition ="2")
//	public Utilisateur getUtilisateur() {
//		return this.utilisateur;
//	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "motdepasse", nullable = false, length = 30)
	public String getMotdepasse() {
		return this.motdepasse;
	}

	public void setMotdepasse(String motdepasse) {
		this.motdepasse = motdepasse;
	}

	@Column(name = "email", nullable = false, length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	public Set<Astuces> getAstuceses() {
		return this.astuceses;
	}

	public void setAstuceses(Set<Astuces> astuceses) {
		this.astuceses = astuceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	public Set<Chat> getChats() {
		return this.chats;
	}

	public void setChats(Set<Chat> chats) {
		this.chats = chats;
	}

}
