package com.neko.model;
// Generated 31 mars 2016 00:28:36 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name = "compte", catalog = "bd")
public class Compte implements java.io.Serializable {

	private String loginCompte;
	private Utilisateur utilisateur;
	private int droit;

	public Compte() {
	}

	public Compte(Utilisateur utilisateur, int droit) {
		this.utilisateur = utilisateur;
		this.droit = droit;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "utilisateur"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "login_compte", unique = true, nullable = false, length = 30)
	public String getLoginCompte() {
		return this.loginCompte;
	}

	public void setLoginCompte(String loginCompte) {
		this.loginCompte = loginCompte;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "droit", nullable = false)
	public int getDroit() {
		return this.droit;
	}

	public void setDroit(int droit) {
		this.droit = droit;
	}

}
