package com.neko.model;
// Generated 2 avr. 2016 23:22:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "chatbd")
public class Utilisateur implements java.io.Serializable {

	private Integer idutilisateur;
	private String droit;
	private Set<Compte> comptes = new HashSet<Compte>(0);

	public Utilisateur() {
	}

	public Utilisateur(String droit) {
		this.droit = droit;
	}

	public Utilisateur(String droit, Set<Compte> comptes) {
		this.droit = droit;
		this.comptes = comptes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idutilisateur", unique = true, nullable = false)
	public Integer getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(Integer idutilisateur) {
		this.idutilisateur = 2;
	}

	@Column(name = "droit", nullable = false, length = 30)
	public String getDroit() {
		return this.droit;
	}

	public void setDroit(String droit) {
		this.droit = droit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Compte> getComptes() {
		return this.comptes;
	}

	public void setComptes(Set<Compte> comptes) {
		this.comptes = comptes;
	}

}
