package com.neko.model;
// Generated 31 mars 2016 00:28:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "bd")
public class Utilisateur implements java.io.Serializable {

	private String login;
	private String modepasse;
	private Compte compte;
	private Set<Astuces> astuceses = new HashSet<Astuces>(0);

	public Utilisateur() {
	}

	public Utilisateur(String login, String modepasse) {
		this.login = login;
		this.modepasse = modepasse;
	}

	public Utilisateur(String login, String modepasse, Compte compte, Set<Astuces> astuceses) {
		this.login = login;
		this.modepasse = modepasse;
		this.compte = compte;
		this.astuceses = astuceses;
	}

	@Id

	@Column(name = "login", unique = true, nullable = false, length = 30)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "modepasse", nullable = false, length = 30)
	public String getModepasse() {
		return this.modepasse;
	}

	public void setModepasse(String modepasse) {
		this.modepasse = modepasse;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Astuces> getAstuceses() {
		return this.astuceses;
	}

	public void setAstuceses(Set<Astuces> astuceses) {
		this.astuceses = astuceses;
	}

}
