package com.neko.model;
// Generated 2 avr. 2016 23:23:44 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Astuces generated by hbm2java
 */
@Entity
@Table(name = "astuces", catalog = "chatbd")
public class Astuces implements java.io.Serializable {

	private Integer idAstuces;
	private Chat chat;
	private Compte compte;
	private String contenu;

	public Astuces() {
	}

	public Astuces(Chat chat, Compte compte, String contenu) {
		this.chat = chat;
		this.compte = compte;
		this.contenu = contenu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_astuces", unique = true, nullable = false)
	public Integer getIdAstuces() {
		return this.idAstuces;
	}

	public void setIdAstuces(Integer idAstuces) {
		this.idAstuces = idAstuces;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nom_chat", nullable = false)
	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login", nullable = false)
	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	@Column(name = "contenu", nullable = false, length = 100)
	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

}
