package com.appliweb.Neko_Atsume.entities;
// Generated 31 mars 2016 05:25:33 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Astuce generated by hbm2java
 */
@Entity
@Table(name = "astuce", catalog = "neko")
public class Astuce implements java.io.Serializable {

	private Integer idAstuce;
	private Chat chat;
	private Compte compte;
	private String contenu;

	public Astuce() {
	}

	public Astuce(Chat chat, Compte compte, String contenu) {
		this.chat = chat;
		this.compte = compte;
		this.contenu = contenu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_astuce", unique = true, nullable = false)
	public Integer getIdAstuce() {
		return this.idAstuce;
	}

	public void setIdAstuce(Integer idAstuce) {
		this.idAstuce = idAstuce;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_chat", nullable = false)
	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_compte", nullable = false)
	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	@Column(name = "contenu", nullable = false, length = 300)
	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

}
