package com.appliweb.Neko_Atsume.entities;
// Generated 29 mars 2016 22:06:27 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chat generated by hbm2java
 */
@Entity
@Table(name = "chat", catalog = "neko")
public class Chat implements java.io.Serializable {

	private Integer idChat;
	private Utilisateur utilisateur;
	private String image;
	private String nomChat;
	private String nomJaponnais;
	private String description;
	private String caractere;
	private int niveau;
	private String memento;
	private String typeChat;
	private Set<Astuce> astuces = new HashSet<Astuce>(0);

	public Chat() {
	}

	public Chat(String image, String nomChat, String nomJaponnais, String description, String caractere, int niveau,
			String memento, String typeChat) {
		this.image = image;
		this.nomChat = nomChat;
		this.nomJaponnais = nomJaponnais;
		this.description = description;
		this.caractere = caractere;
		this.niveau = niveau;
		this.memento = memento;
		this.typeChat = typeChat;
	}

	public Chat(Utilisateur utilisateur, String image, String nomChat, String nomJaponnais, String description,
			String caractere, int niveau, String memento, String typeChat, Set<Astuce> astuces) {
		this.utilisateur = utilisateur;
		this.image = image;
		this.nomChat = nomChat;
		this.nomJaponnais = nomJaponnais;
		this.description = description;
		this.caractere = caractere;
		this.niveau = niveau;
		this.memento = memento;
		this.typeChat = typeChat;
		this.astuces = astuces;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_chat", unique = true, nullable = false)
	public Integer getIdChat() {
		return this.idChat;
	}

	public void setIdChat(Integer idChat) {
		this.idChat = idChat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_utilisateur")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "image", nullable = false, length = 100)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "nom_chat", nullable = false, length = 30)
	public String getNomChat() {
		return this.nomChat;
	}

	public void setNomChat(String nomChat) {
		this.nomChat = nomChat;
	}

	@Column(name = "nom_japonnais", nullable = false, length = 30)
	public String getNomJaponnais() {
		return this.nomJaponnais;
	}

	public void setNomJaponnais(String nomJaponnais) {
		this.nomJaponnais = nomJaponnais;
	}

	@Column(name = "description", nullable = false, length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "caractere", nullable = false, length = 65535)
	public String getCaractere() {
		return this.caractere;
	}

	public void setCaractere(String caractere) {
		this.caractere = caractere;
	}

	@Column(name = "niveau", nullable = false)
	public int getNiveau() {
		return this.niveau;
	}

	public void setNiveau(int niveau) {
		this.niveau = niveau;
	}

	@Column(name = "memento", nullable = false, length = 50)
	public String getMemento() {
		return this.memento;
	}

	public void setMemento(String memento) {
		this.memento = memento;
	}

	@Column(name = "type_chat", nullable = false, length = 50)
	public String getTypeChat() {
		return this.typeChat;
	}

	public void setTypeChat(String typeChat) {
		this.typeChat = typeChat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chat")
	public Set<Astuce> getAstuces() {
		return this.astuces;
	}

	public void setAstuces(Set<Astuce> astuces) {
		this.astuces = astuces;
	}

}
