package com.appliweb.Neko_Atsume.entities;
// Generated 31 mars 2016 17:29:47 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chat generated by hbm2java
 */
@Entity
@Table(name = "chat", catalog = "neko")
public class Chat implements java.io.Serializable {

	private int idChat;
	private String image;
	private String nomChat;
	private String nomJaponnais;
	private String description;
	private String caractere;
	private Integer niveau;
	private String memento;
	private String typeChat;
	private Set<Compte> comptes = new HashSet<Compte>(0);
	private Set<Astuce> astuces = new HashSet<Astuce>(0);

	public Chat() {
	}

	public Chat(int idChat) {
		this.idChat = idChat;
	}

	public Chat(int idChat, String image, String nomChat, String nomJaponnais, String description, String caractere,
			Integer niveau, String memento, String typeChat, Set<Compte> comptes, Set<Astuce> astuces) {
		this.idChat = idChat;
		this.image = image;
		this.nomChat = nomChat;
		this.nomJaponnais = nomJaponnais;
		this.description = description;
		this.caractere = caractere;
		this.niveau = niveau;
		this.memento = memento;
		this.typeChat = typeChat;
		this.comptes = comptes;
		this.astuces = astuces;
	}

	@Id

	@Column(name = "id_chat", unique = true, nullable = false)
	public int getIdChat() {
		return this.idChat;
	}

	public void setIdChat(int idChat) {
		this.idChat = idChat;
	}

	@Column(name = "image", length = 10)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "nom_chat", length = 18)
	public String getNomChat() {
		return this.nomChat;
	}

	public void setNomChat(String nomChat) {
		this.nomChat = nomChat;
	}

	@Column(name = "nom_japonnais", length = 24)
	public String getNomJaponnais() {
		return this.nomJaponnais;
	}

	public void setNomJaponnais(String nomJaponnais) {
		this.nomJaponnais = nomJaponnais;
	}

	@Column(name = "description", length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "caractere", length = 16)
	public String getCaractere() {
		return this.caractere;
	}

	public void setCaractere(String caractere) {
		this.caractere = caractere;
	}

	@Column(name = "niveau")
	public Integer getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Integer niveau) {
		this.niveau = niveau;
	}

	@Column(name = "memento", length = 10)
	public String getMemento() {
		return this.memento;
	}

	public void setMemento(String memento) {
		this.memento = memento;
	}

	@Column(name = "type_chat", length = 12)
	public String getTypeChat() {
		return this.typeChat;
	}

	public void setTypeChat(String typeChat) {
		this.typeChat = typeChat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chat")
	public Set<Compte> getComptes() {
		return this.comptes;
	}

	public void setComptes(Set<Compte> comptes) {
		this.comptes = comptes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chat")
	public Set<Astuce> getAstuces() {
		return this.astuces;
	}

	public void setAstuces(Set<Astuce> astuces) {
		this.astuces = astuces;
	}

}
