package com.appliweb.Neko_Atsume.entities;
// Generated 31 mars 2016 17:29:47 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compte generated by hbm2java
 */
@Entity
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="type_cpte",discriminatorType=DiscriminatorType.STRING,length=4)
@Table(name = "compte", catalog = "neko")
public class Compte implements java.io.Serializable {

	private Integer idCompte;
	private Chat chat;
	private Utilisateur utilisateur;
	private String typeCpte;
	private Date dateCreation;
	private Set<Astuce> astuces = new HashSet<Astuce>(0);

	public Compte() {
	}

	public Compte(Utilisateur utilisateur, String typeCpte, Date dateCreation) {
		this.utilisateur = utilisateur;
		this.typeCpte = typeCpte;
		this.dateCreation = dateCreation;
	}

	public Compte(Chat chat, Utilisateur utilisateur, String typeCpte, Date dateCreation, Set<Astuce> astuces) {
		this.chat = chat;
		this.utilisateur = utilisateur;
		this.typeCpte = typeCpte;
		this.dateCreation = dateCreation;
		this.astuces = astuces;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_compte", unique = true, nullable = false)
	public Integer getIdCompte() {
		return this.idCompte;
	}

	public void setIdCompte(Integer idCompte) {
		this.idCompte = idCompte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_chat")
	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "type_cpte", nullable = false, length = 50)
	public String getTypeCpte() {
		return this.typeCpte;
	}

	public void setTypeCpte(String typeCpte) {
		this.typeCpte = typeCpte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_creation", nullable = false, length = 10)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	public Set<Astuce> getAstuces() {
		return this.astuces;
	}

	public void setAstuces(Set<Astuce> astuces) {
		this.astuces = astuces;
	}

}
