package com.appliweb.Neko_Atsume.entities;
// Generated 31 mars 2016 05:25:33 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "neko")
public class Utilisateur implements java.io.Serializable {

	private String login;
	private String motdepasse;
	private Set<Compte> comptes = new HashSet<Compte>(0);

	public Utilisateur() {
	}

	public Utilisateur(String login, String motdepasse) {
		this.login = login;
		this.motdepasse = motdepasse;
	}

	public Utilisateur(String login, String motdepasse, Set<Compte> comptes) {
		this.login = login;
		this.motdepasse = motdepasse;
		this.comptes = comptes;
	}

	@Id

	@Column(name = "login", unique = true, nullable = false, length = 30)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "motdepasse", nullable = false, length = 30)
	public String getMotdepasse() {
		return this.motdepasse;
	}

	public void setMotdepasse(String motdepasse) {
		this.motdepasse = motdepasse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Compte> getComptes() {
		return this.comptes;
	}

	public void setComptes(Set<Compte> comptes) {
		this.comptes = comptes;
	}

}
