package projet.neko.model;
// Generated 27 mars 2016 17:00:36 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Astuce generated by hbm2java
 */
@Entity
@Table(name="astuce"
    ,catalog="neko"
)
public class Astuce  implements java.io.Serializable {


     private Integer idAvis;
     private Chat chat;
     private Utilisateur utilisateur;
     private String commentaire;
     private int nombreDeVote;

    public Astuce() {
    }

    public Astuce(Chat chat, Utilisateur utilisateur, String commentaire, int nombreDeVote) {
       this.chat = chat;
       this.utilisateur = utilisateur;
       this.commentaire = commentaire;
       this.nombreDeVote = nombreDeVote;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_avis", unique=true, nullable=false)
    public Integer getIdAvis() {
        return this.idAvis;
    }
    
    public void setIdAvis(Integer idAvis) {
        this.idAvis = idAvis;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_chat", nullable=false)
    public Chat getChat() {
        return this.chat;
    }
    
    public void setChat(Chat chat) {
        this.chat = chat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_utilisateur", nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="commentaire", nullable=false, length=100)
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }

    
    @Column(name="nombre_de_vote", nullable=false)
    public int getNombreDeVote() {
        return this.nombreDeVote;
    }
    
    public void setNombreDeVote(int nombreDeVote) {
        this.nombreDeVote = nombreDeVote;
    }




}


