package projet.neko.model;
// Generated 27 mars 2016 17:00:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeUtilisateur generated by hbm2java
 */
@Entity
@Table(name="type_utilisateur"
    ,catalog="neko"
)
public class TypeUtilisateur  implements java.io.Serializable {


     private Integer idType;
     private String typeUtilisateur;
     private Set utilisateurs = new HashSet(0);

    public TypeUtilisateur() {
    }

	
    public TypeUtilisateur(String typeUtilisateur) {
        this.typeUtilisateur = typeUtilisateur;
    }
    public TypeUtilisateur(String typeUtilisateur, Set utilisateurs) {
       this.typeUtilisateur = typeUtilisateur;
       this.utilisateurs = utilisateurs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_type", unique=true, nullable=false)
    public Integer getIdType() {
        return this.idType;
    }
    
    public void setIdType(Integer idType) {
        this.idType = idType;
    }

    
    @Column(name="type_utilisateur", nullable=false, length=30)
    public String getTypeUtilisateur() {
        return this.typeUtilisateur;
    }
    
    public void setTypeUtilisateur(String typeUtilisateur) {
        this.typeUtilisateur = typeUtilisateur;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typeUtilisateur")
    public Set getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set utilisateurs) {
        this.utilisateurs = utilisateurs;
    }




}


